const http=require("http"),fs=require("fs"),path=require("path"),https=require("https");
const root=path.join(__dirname,"public"),dataDir=process.env.DATA_DIR||path.join(__dirname,"data"),queueFile=path.join(dataDir,"approval.json"),port=process.env.PORT||3000;
if(!fs.existsSync(dataDir))fs.mkdirSync(dataDir,{recursive:true});if(!fs.existsSync(queueFile))fs.writeFileSync(queueFile,"[]");
const queueRead=()=>{try{return JSON.parse(fs.readFileSync(queueFile,"utf8"))}catch{return[]}};const queueWrite=x=>fs.writeFileSync(queueFile,JSON.stringify(x,null,2));
const safeText=x=>String(x||"").replace(/[<>]/g,"").trim(),slugify=x=>safeText(x).toLowerCase().replace(/[^a-z0-9ก-๙]+/g,"-").replace(/^-|-$/g,"").slice(0,100);
const escapeHtml=x=>String(x||"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]));
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
const BUSINESS_PROFILE={name:"ห้างหุ้นส่วนจำกัด แอเรีย ไม้แบบ",alternateName:"AREA Maibab",url:(process.env.PUBLIC_SITE_URL||"https://area-maibab-public-site.onrender.com").replace(/\/$/,""),telephone:"+66-64-989-3124",primaryArea:"อำเภอแม่สาย",region:"เชียงราย",country:"TH"};
const verifiedBusinessSchema=()=>({"@context":"https://schema.org","@type":["LocalBusiness","Store"],"@id":BUSINESS_PROFILE.url+"/#organization",name:BUSINESS_PROFILE.name,alternateName:BUSINESS_PROFILE.alternateName,url:BUSINESS_PROFILE.url,telephone:BUSINESS_PROFILE.telephone,description:"บริการให้เช่าไม้แบบพลาสติก นั่งร้าน และเครื่องมือก่อสร้าง โดยมีอำเภอแม่สายเป็นพื้นที่หลัก",areaServed:[{"@type":"AdministrativeArea",name:BUSINESS_PROFILE.primaryArea}],hasOfferCatalog:{"@type":"OfferCatalog",name:"บริการเช่าอุปกรณ์ก่อสร้าง",itemListElement:[{"@type":"Offer",itemOffered:{"@type":"Service",name:"เช่าไม้แบบพลาสติก แม่สาย"}},{"@type":"Offer",itemOffered:{"@type":"Service",name:"เช่านั่งร้านและอุปกรณ์ประกอบ"}},{"@type":"Offer",itemOffered:{"@type":"Service",name:"เช่าเครื่องมือก่อสร้าง"}}]}});

const renderPreview=x=>'<!doctype html><html lang="th"><head><meta charset="utf-8"><meta name="robots" content="noindex,nofollow"><title>'+escapeHtml(x.title)+'</title><meta name="description" content="'+escapeHtml(x.meta)+'"></head><body><main>'+String(x.content||"").split("\n").filter(Boolean).map(l=>l.startsWith("## ")?("<h2>"+escapeHtml(l.slice(3))+"</h2>"):("<p>"+escapeHtml(l)+"</p>")).join("\n")+"</main></body></html>";
const markdownHtml=md=>String(md||"").split("\n").filter(Boolean).map(l=>l.startsWith("### ")?("<h3>"+escapeHtml(l.slice(4))+"</h3>"):l.startsWith("## ")?("<h2>"+escapeHtml(l.slice(3))+"</h2>"):l.startsWith("- ")?("<p>• "+escapeHtml(l.slice(2))+"</p>"):("<p>"+escapeHtml(l)+"</p>")).join("\n");
const articleDocument=item=>{const base=(process.env.PUBLIC_SITE_URL||"https://area-maibab-public-site.onrender.com").replace(/\/$/,""),filename="article-"+item.slug+".html",canonical=base+"/"+filename,schema={"@context":"https://schema.org","@type":"Article",headline:item.title,description:item.meta,inLanguage:"th-TH",mainEntityOfPage:canonical,author:{"@type":"Organization","name":"AREA Maibab"},publisher:{"@type":"Organization","name":"AREA Maibab","url":base}};return{filename,canonical,html:'<!doctype html><html lang="th"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>'+escapeHtml(item.title)+'</title><meta name="description" content="'+escapeHtml(item.meta)+'"><link rel="canonical" href="'+escapeHtml(canonical)+'"><script type="application/ld+json">'+JSON.stringify(schema).replace(/</g,"\\u003c")+'</script><link rel="stylesheet" href="style.css"></head><body><main class="article"><article>'+markdownHtml(item.content)+'</article></main></body></html>'}};
const updateSitemap=(xml,url)=>xml.includes("<loc>"+url+"</loc>")?xml:xml.replace("</urlset>","  <url>\n    <loc>"+escapeHtml(url)+"</loc>\n  </url>\n</urlset>");
const buildPublishPlan=(item,pre)=>({mode:"dry-run",targetRepo:process.env.PUBLISH_REPO||"jmmeta6767/area-maibab-public-site",branch:process.env.PUBLISH_BRANCH||"main",articlePath:pre.filename,requiredUpdates:[pre.filename,"articles.html","sitemap.xml"],rollback:"revert single publish commit",generatedAt:new Date().toISOString()});
const get=url=>new Promise((ok,no)=>{const q=https.get(url,{headers:{"User-Agent":"AREA-SEO-AI/0.9"}},r=>{let d="";r.on("data",c=>{d+=c;if(d.length>2e6)q.destroy(Error("Remote response too large"))});r.on("end",()=>r.statusCode>=200&&r.statusCode<300?ok(d):no(Error("HTTP "+r.statusCode)))});q.setTimeout(12000,()=>q.destroy(Error("Remote request timeout")));q.on("error",no)});
async function scanSite(){const base=process.env.PUBLIC_SITE_URL||"https://area-maibab-public-site.onrender.com",xml=await get(base+"/sitemap.xml"),urls=[...xml.matchAll(/<loc>(.*?)<\/loc>/g)].map(x=>x[1]),articleUrls=urls.filter(x=>/article-|guide-/.test(x)),titles=[];for(const url of articleUrls.slice(0,24)){try{let h=await get(url),m=h.match(/<title[^>]*>([^<]+)<\/title>/i);titles.push({url,title:(m?.[1]||url.split("/").pop()).replace(/\s+/g," ").trim()})}catch{}}return{site:base,pages:urls.length,articles:articleUrls.length,servicePages:urls.filter(x=>/(rent|scaffolding|tools|service-area)/.test(x)).length,sample:urls.slice(0,8),articleIndex:titles,scannedAt:new Date().toISOString()}}
const publishPreflight=async item=>{let scan=await scanSite(),filename="article-"+item.slug+".html",duplicate=scan.articleIndex.some(x=>x.url.endsWith("/"+filename)||x.url.endsWith(filename));return{ok:item.status==="approved"&&!duplicate&&item.audit?.passed===true,filename,duplicate,approved:item.status==="approved",auditPassed:item.audit?.passed===true,checks:[{ok:item.status==="approved",label:"Human approval"},{ok:item.audit?.passed===true,label:"SEO audit passed"},{ok:!duplicate,label:"Unique article slug"},{ok:true,label:"Preview HTML escaped / no raw script injection"}]}};
const headers={"Content-Type":"application/json; charset=utf-8","Cache-Control":"no-store","X-Content-Type-Options":"nosniff","Referrer-Policy":"no-referrer","X-Frame-Options":"DENY"};
const json=(res,code,data)=>{res.writeHead(code,headers);res.end(JSON.stringify(data))};
const aiTimes=[];const aiLimit=()=>{let now=Date.now();while(aiTimes.length&&aiTimes[0]<now-60000)aiTimes.shift();if(aiTimes.length>=10){let e=Error("คำขอ AI มากเกินไป กรุณารอสักครู่");e.status=429;throw e}aiTimes.push(now)};
const body=req=>new Promise((ok,no)=>{let d="",done=false;req.on("data",c=>{if(done)return;d+=c;if(Buffer.byteLength(d)>1e6){done=true;let e=Error("Request body too large");e.status=413;no(e)}});req.on("end",()=>{if(done)return;try{ok(d?JSON.parse(d):{})}catch(e){e.status=400;no(e)}});req.on("error",no)});
function localAudit(x){let score=0,checks=[],title=String(x.title||"").trim(),meta=String(x.meta||"").trim(),content=String(x.content||""),slug=String(x.slug||"").replace(/^\/+|\/+$/g,""),schema=x.schema;const add=(ok,pts,label)=>{if(ok)score+=pts;checks.push({ok,label})};add(title.length>=50&&title.length<=60,10,"Meta title 50–60 characters");add(meta.length>=130&&meta.length<=150,15,"Meta description 130–150 characters");add(content.includes("แม่สาย"),10,"Mae Sai local context");add((content.match(/^# /gm)||[]).length===1,10,"Exactly one H1");let h2=(content.match(/^## /gm)||[]).length;add(h2>=2&&h2<=4,10,"2–4 H2 sections");add(/^- /m.test(content),5,"Bullet list present");add(/^\s*\|.+\|\s*$/m.test(content),5,"Comparison table present");add(content.length>=2500,10,"Long-form article body");add(/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(slug),5,"English lowercase URL slug");add(!!x.imagePrompt&&!!x.imageAlt,5,"Featured image prompt + ALT");add(!!x.cta,5,"CTA block present");let schemaOk=false;try{let s=typeof schema==="string"?JSON.parse(schema):schema;schemaOk=!!s&&s["@context"]==="https://schema.org"&&["Article","LocalBusiness"].includes(s["@type"])}catch{}add(schemaOk,5,"Valid JSON-LD schema");add(!/(ส่งทั่วเชียงราย|บริการทั่วเชียงราย|จัดส่งเชียงรายทั้งหมด|ให้บริการทั่วเชียงราย)/.test(content),5,"No unsupported Chiang Rai-wide service claim");return{score,checks,passed:score>=85&&checks.filter(c=>["English lowercase URL slug","Valid JSON-LD schema","No unsupported Chiang Rai-wide service claim","Exactly one H1"].includes(c.label)).every(c=>c.ok)}}
const normalizeAI=x=>JSON.parse(JSON.stringify(x||{}).replace(/\uFFFD/g,""));
async function gemini(prompt){aiLimit();const key=process.env.GEMINI_API_KEY;if(!key){let e=Error("GEMINI_API_KEY is not configured");e.status=503;throw e}const models=[process.env.GEMINI_MODEL||"gemini-flash-latest","gemini-2.5-flash"].filter((x,i,a)=>a.indexOf(x)===i);let last;for(const model of models){for(let attempt=0;attempt<3;attempt++){try{return await geminiOnce(model,key,prompt)}catch(e){last=e;if(![429,500,502,503,504].includes(e.statusCode||0))throw e;if(attempt<2)await sleep(700*Math.pow(2,attempt))}}}let e=Error("Gemini กำลังมีผู้ใช้งานจำนวนมาก ระบบลองใหม่แล้ว กรุณาลองอีกครั้งในอีกสักครู่");e.status=503;e.cause=last;throw e}
function geminiOnce(model,key,prompt){const payload=JSON.stringify({contents:[{parts:[{text:prompt}]}],generationConfig:{responseMimeType:"application/json"}});return new Promise((ok,no)=>{const req=https.request({hostname:"generativelanguage.googleapis.com",path:"/v1beta/models/"+encodeURIComponent(model)+":generateContent",method:"POST",headers:{"Content-Type":"application/json","Content-Length":Buffer.byteLength(payload),"X-goog-api-key":key}},r=>{let d="";r.on("data",c=>d+=c);r.on("end",()=>{try{let j=JSON.parse(d);if(r.statusCode<200||r.statusCode>=300){let e=Error(j.error?.message||"Gemini HTTP "+r.statusCode);e.statusCode=r.statusCode;return no(e)}let raw=j.candidates?.[0]?.content?.parts?.[0]?.text||"{}";ok(normalizeAI(JSON.parse(raw)))}catch(e){no(e)}})});req.setTimeout(30000,()=>req.destroy(Error("Gemini timeout")));req.on("error",no);req.end(payload)})}
const intelligence=require("./lib/site-intelligence").createIntelligence({dataDir,base:BUSINESS_PROFILE.url});
const qualityAuditor=require("./lib/content-quality");
const publicPublisher=require("./lib/public-site-publisher");
const prPublisher=require("./lib/github-pr-publisher").createClient();
const adminAuth=require("./lib/admin-auth").createAdminAuth();
const api=async(req,res,u)=>{try{
if(req.method==="GET"&&u.pathname==="/api/admin/backup")return json(res,200,{schema_version:"1",exported_at:new Date().toISOString(),approvals:queueRead(),site_history:intelligence.history(),storage:intelligence.status()});
if(req.method==="POST"&&u.pathname==="/api/seo/quality-review")return json(res,200,await qualityAuditor.reviewArticle(await body(req),gemini));
if(req.method==="GET"&&u.pathname==="/api/intelligence/history")return json(res,200,{items:intelligence.history(),latest:intelligence.latest(),...intelligence.status()});
if(req.method==="POST"&&u.pathname==="/api/intelligence/scan")return json(res,201,await intelligence.scan());
if(req.method==="GET"&&u.pathname.startsWith("/api/intelligence/snapshot/")){let item=intelligence.detail(u.pathname.split("/").pop());return item?json(res,200,item):json(res,404,{error:"Snapshot not found"})}

if(req.method==="GET"&&u.pathname==="/api/business-profile")return json(res,200,{profile:BUSINESS_PROFILE,schema:verifiedBusinessSchema()});
if(req.method==="GET"&&u.pathname==="/api/health")return json(res,200,{ok:true,version:"1.9.0",geminiConfigured:!!process.env.GEMINI_API_KEY,publisherConfigured:prPublisher.configured,authRequired:adminAuth.required,authConfigured:adminAuth.configured,target:process.env.PUBLIC_SITE_URL||"https://area-maibab-public-site.onrender.com"});
if(req.method==="POST"&&u.pathname==="/api/site/scan")return json(res,200,await scanSite());if(req.method==="GET"&&u.pathname==="/api/approval")return json(res,200,{items:queueRead()});
if(req.method==="GET"&&/^\/api\/approval\/[^/]+\/preview$/.test(u.pathname)){let id=u.pathname.split("/")[3],item=queueRead().find(x=>x.id===id);if(!item)return json(res,404,{error:"Draft not found"});res.writeHead(200,{"Content-Type":"text/html; charset=utf-8","Content-Security-Policy":"default-src 'none'; style-src 'unsafe-inline'; img-src data:;","X-Content-Type-Options":"nosniff"});return res.end(renderPreview(item))}
if(req.method==="POST"&&/^\/api\/approval\/[^/]+\/preflight$/.test(u.pathname)){let item=queueRead().find(x=>x.id===u.pathname.split("/")[3]);if(!item)return json(res,404,{error:"Draft not found"});let pre=await publishPreflight(item);return json(res,200,{...pre,plan:pre.ok?buildPublishPlan(item,pre):null})}
if(req.method==="GET"&&/^\/api\/approval\/[^/]+\/artifact$/.test(u.pathname)){let item=queueRead().find(x=>x.id===u.pathname.split("/")[3]);if(!item)return json(res,404,{error:"Draft not found"});let pre=await publishPreflight(item);if(!pre.ok)return json(res,422,{error:"Preflight failed",...pre});let doc=articleDocument(item);return json(res,200,{filename:doc.filename,canonical:doc.canonical,html:doc.html,sitemapPreview:updateSitemap('<?xml version="1.0" encoding="UTF-8"?><urlset></urlset>',doc.canonical)})}
if(req.method==="GET"&&/^\/api\/approval\/[^/]+\/publisher-package$/.test(u.pathname)){let item=queueRead().find(x=>x.id===u.pathname.split("/")[3]);if(!item)return json(res,404,{error:"Draft not found"});let pre=await publishPreflight(item);if(!pre.ok)return json(res,422,{error:"Preflight failed",...pre});let base=BUSINESS_PROFILE.url,[articlesHtml,sitemapXml]=await Promise.all([get(base+"/articles.html"),get(base+"/sitemap.xml")]);let pkg=publicPublisher.buildPublishPackage(item,{articlesHtml,sitemapXml},{baseUrl:base,publishedAt:new Date().toISOString()});return json(res,200,{mode:"package-only",targetRepo:process.env.PUBLISH_REPO||"jmmeta6767/area-maibab-public-site",targetBranch:process.env.PUBLISH_BRANCH||"main",checks:pkg.checks,files:pkg.files.map(x=>({path:x.path,bytes:Buffer.byteLength(x.content),content:x.content}))})}
if(req.method==="POST"&&/^\/api\/approval\/[^/]+\/publish-pr$/.test(u.pathname)){let id=u.pathname.split("/")[3],q=queueRead(),idx=q.findIndex(x=>x.id===id);if(idx<0)return json(res,404,{error:"Draft not found"});let item=q[idx],pre=await publishPreflight(item);if(!pre.ok)return json(res,422,{error:"Publisher preflight failed",...pre});let base=BUSINESS_PROFILE.url,[articlesHtml,sitemapXml]=await Promise.all([get(base+"/articles.html"),get(base+"/sitemap.xml")]);let pkg=publicPublisher.buildPublishPackage(item,{articlesHtml,sitemapXml},{baseUrl:base,publishedAt:new Date().toISOString()});let result=await prPublisher.createPublishPR(item,pkg);q[idx].status="publishing";q[idx].publish={...result,createdAt:new Date().toISOString()};queueWrite(q);return json(res,201,{...result,status:q[idx].status})}
if(req.method==="GET"&&/^\\/api\\/approval\\/[^/]+\\/publish-status$/.test(u.pathname)){let id=u.pathname.split("/")[3],q=queueRead(),idx=q.findIndex(x=>x.id===id);if(idx<0)return json(res,404,{error:"Draft not found"});let item=q[idx],number=item.publish?.pr?.number;if(!number)return json(res,409,{error:"No publisher pull request recorded for this draft"});let status=await prPublisher.getPublishStatus(number);q[idx].publish={...item.publish,lastStatus:status,checkedAt:new Date().toISOString()};if(status.merged)q[idx].status="published";else if(status.state==="closed")q[idx].status="needs_changes";else q[idx].status="publishing";queueWrite(q);return json(res,200,{draftStatus:q[idx].status,...status})}\nif(req.method==="POST"&&/^\/api\/approval\/[^/]+\/publish$/.test(u.pathname)){let item=queueRead().find(x=>x.id===u.pathname.split("/")[3]);if(!item)return json(res,404,{error:"Draft not found"});let pre=await publishPreflight(item);if(!pre.ok)return json(res,422,{error:"Publisher preflight failed",...pre});return json(res,423,{error:"Live publisher is intentionally locked until integration tests pass",plan:buildPublishPlan(item,pre)})}
if(req.method==="POST"&&u.pathname==="/api/approval"){let x=await body(req),a=localAudit(x);if(!a.passed)return json(res,422,{error:"SEO audit must pass before approval queue",audit:a});let q=queueRead(),item={id:"draft-"+Date.now(),status:"ready_for_review",title:safeText(x.title),meta:safeText(x.meta),content:String(x.content||""),service:safeText(x.service),slug:x.slug?slugify(x.slug):slugify(x.title),imagePrompt:safeText(x.imagePrompt),imageAlt:safeText(x.imageAlt),cta:x.cta||"",schema:x.schema||{},audit:a,createdAt:new Date().toISOString(),versions:[{at:new Date().toISOString(),title:safeText(x.title),meta:safeText(x.meta),content:String(x.content||"")}]};q.unshift(item);queueWrite(q);return json(res,201,item)}
if(req.method==="POST"&&/^\/api\/approval\/[^/]+\/(approve|reject)$/.test(u.pathname)){let [,, ,id,action]=u.pathname.split("/"),q=queueRead(),i=q.findIndex(x=>x.id===id);if(i<0)return json(res,404,{error:"Draft not found"});q[i].status=action==="approve"?"approved":"needs_changes";q[i][action==="approve"?"approvedAt":"rejectedAt"]=new Date().toISOString();queueWrite(q);return json(res,200,q[i])}
if(req.method==="POST"&&u.pathname==="/api/seo/audit")return json(res,200,localAudit(await body(req)));
if(req.method==="POST"&&u.pathname==="/api/content/gaps"){let x=await body(req),scan=await scanSite(),prompt=`Analyze existing AREA Maibab article titles and suggest 5 NON-DUPLICATE Thai local SEO content gaps for service "${x.service||"construction equipment rental"}" in Mae Sai. Do not target Chiang Rai city and do not invent facts. Existing: ${JSON.stringify(scan.articleIndex)}. Return JSON with key gaps, each item: topic, primaryKeyword, intent, reason, suggestedInternalLink.`;return json(res,200,await gemini(prompt))}
if(req.method==="POST"&&u.pathname==="/api/seo/fix"){let x=await body(req),a=localAudit(x),prompt=`Improve this Thai AREA Maibab article while preserving factual claims. Primary market Mae Sai only. Never invent price, stock, review, delivery coverage, phone, promotion, or business facts. Fix SEO issues: ${JSON.stringify(a.checks.filter(c=>!c.ok))}. Return the complete corrected JSON object with title, meta, content, slug, imagePrompt, imageAlt, cta and schema. Preserve valid fields and repair missing ones without inventing facts. INPUT: ${JSON.stringify(x)}`;let fixed={...x,...await gemini(prompt)};return json(res,200,{...fixed,audit:localAudit(fixed)})}
if(req.method==="POST"&&u.pathname==="/api/content/generate"){let x=await body(req),prompt=`You are AREA SEO Content Engine, a Thai Local SEO specialist for construction equipment and formwork rental. Confirmed primary service market: Amphoe Mae Sai, Chiang Rai province. Mae Chan, Chiang Saen and Chiang Rai city may be mentioned only as geographic or construction context; NEVER claim AREA Maibab delivers to or serves those places unless verified business data explicitly says so. Never invent prices, stock, reviews, promotions, phone numbers, addresses, LINE URLs, Facebook URLs, service coverage, or business facts. Generate 800-1200 Thai words. Return valid JSON only with keys: title, meta, slug, primaryKeyword, secondaryKeywords, intent, imagePrompt, imageAlt, content, cta, schema. Requirements: title 50-60 characters and include primary keyword plus Mae Sai or Chiang Rai where natural; meta 130-150 characters with a factual CTA that does not invent contact details; slug English lowercase hyphenated; 3-5 secondaryKeywords; content Markdown with exactly one H1, 2-4 H2, H3 as useful, bullets and a comparison table; solve contractor pain points without asserting unverified product properties; include natural local context; CTA must use placeholders for any unverified contact fields; schema must be a JSON object of type Article and must not contain invented business data. LocalBusiness identity belongs to the PUBLIC_SITE_URL, never to this admin app. If business address, geo, opening hours, telephone, image, or areaServed are not supplied as verified business data, omit them rather than guessing. Use LocalBusiness for local business markup unless a verified, valid more-specific schema.org subtype is configured. Service: ${x.service||"construction equipment rental"}. Topic: ${x.topic||"choose a useful non-duplicate local customer question"}.`;let out=await gemini(prompt);out.content=String(out.content||"").replace(/\uFFFD/g,"");out.title=safeText(out.title);out.meta=safeText(out.meta);out.slug=String(out.slug||"").toLowerCase().replace(/^\/+|\/+$/g,"").replace(/[^a-z0-9-]/g,"").replace(/-+/g,"-");out.secondaryKeywords=Array.isArray(out.secondaryKeywords)?out.secondaryKeywords.slice(0,5).map(safeText):[];return json(res,200,out)}
return json(res,404,{error:"API not found"});}catch(e){return json(res,e.status||500,{error:e.message})}};
const server=http.createServer((req,res)=>{const u=new URL(req.url,"http://localhost");if(u.pathname!=="/api/health"){const gate=adminAuth.check(req);if(!gate.ok)return adminAuth.reject(res,gate)}if(u.pathname.startsWith("/api/"))return api(req,res,u);let rel=u.pathname==="/"?"/index.html":u.pathname,file=path.normalize(path.join(root,rel));if(!file.startsWith(root)){res.writeHead(403);return res.end("Forbidden")}fs.readFile(file,(e,d)=>{if(e){res.writeHead(404);return res.end("Not found")}res.setHeader("X-Content-Type-Options","nosniff");res.setHeader("Referrer-Policy","no-referrer");res.setHeader("Content-Type",file.endsWith(".css")?"text/css":file.endsWith(".js")?"text/javascript; charset=utf-8":"text/html; charset=utf-8");res.end(d)})});
if(require.main===module)server.listen(port,()=>console.log("AREA SEO AI v1.9.0 : "+port));
module.exports={server,localAudit,articleDocument,updateSitemap,escapeHtml,slugify};

