const http=require("http"),fs=require("fs"),path=require("path"),https=require("https");
const root=path.join(__dirname,"public"),port=process.env.PORT||3000;
const json=(res,code,data)=>{res.writeHead(code,{"Content-Type":"application/json; charset=utf-8","Cache-Control":"no-store"});res.end(JSON.stringify(data))};
const body=req=>new Promise((ok,no)=>{let d="";req.on("data",c=>{d+=c;if(d.length>1e6)req.destroy()});req.on("end",()=>{try{ok(d?JSON.parse(d):{})}catch(e){no(e)}})});
function get(url){return new Promise((ok,no)=>{https.get(url,{headers:{"User-Agent":"AREA-SEO-AI/0.2"}},r=>{let d="";r.on("data",c=>d+=c);r.on("end",()=>r.statusCode>=200&&r.statusCode<300?ok(d):no(Error("HTTP "+r.statusCode)))}).on("error",no)})}
async function scanSite(){const base=process.env.PUBLIC_SITE_URL||"https://area-maibab-public-site.onrender.com";let xml=await get(base+"/sitemap.xml");let urls=[...xml.matchAll(/<loc>(.*?)<\/loc>/g)].map(x=>x[1]);return{site:base,pages:urls.length,articles:urls.filter(x=>/article-|guide-/.test(x)).length,servicePages:urls.filter(x=>/(rent|scaffolding|tools|service-area)/.test(x)).length,sample:urls.slice(0,8),scannedAt:new Date().toISOString()}}
function localAudit(x){let score=0,checks=[];const title=(x.title||"").trim(),meta=(x.meta||"").trim(),content=x.content||"";const add=(ok,pts,label)=>{if(ok)score+=pts;checks.push({ok,label})};add(title.length>20&&title.length<=60,20,"SEO title 20–60 characters");add(meta.length>=100&&meta.length<=160,20,"Meta description 100–160 characters");add(content.includes("แม่สาย"),20,"Mae Sai local context");add((content.match(/^## /gm)||[]).length>=2,15,"Useful H2 structure");add(content.length>=600,10,"Substantial draft");add(!/(ส่งทั่วเชียงราย|บริการทั่วเชียงราย|จัดส่งเชียงรายทั้งหมด)/.test(content),15,"No unsupported Chiang Rai-wide service claim");return{score,checks,passed:score>=80}}
async function gemini(prompt){const key=process.env.GEMINI_API_KEY;if(!key)throw Error("GEMINI_API_KEY is not configured");const model=process.env.GEMINI_MODEL||"gemini-2.5-flash";const payload=JSON.stringify({contents:[{parts:[{text:prompt}]}],generationConfig:{responseMimeType:"application/json"}});return new Promise((ok,no)=>{const req=https.request({hostname:"generativelanguage.googleapis.com",path:"/v1beta/models/"+model+":generateContent?key="+encodeURIComponent(key),method:"POST",headers:{"Content-Type":"application/json","Content-Length":Buffer.byteLength(payload)}},r=>{let d="";r.on("data",c=>d+=c);r.on("end",()=>{try{let j=JSON.parse(d);if(r.statusCode<200||r.statusCode>=300)return no(Error(j.error?.message||"Gemini HTTP "+r.statusCode));ok(JSON.parse(j.candidates?.[0]?.content?.parts?.[0]?.text||"{}"))}catch(e){no(e)}})});req.on("error",no);req.end(payload)})}
const api=async(req,res,u)=>{try{
 if(req.method==="GET"&&u.pathname==="/api/health")return json(res,200,{ok:true,version:"0.2.0",geminiConfigured:!!process.env.GEMINI_API_KEY,target:process.env.PUBLIC_SITE_URL||"https://area-maibab-public-site.onrender.com"});
 if(req.method==="POST"&&u.pathname==="/api/site/scan")return json(res,200,await scanSite());
 if(req.method==="POST"&&u.pathname==="/api/seo/audit")return json(res,200,localAudit(await body(req)));
 if(req.method==="POST"&&u.pathname==="/api/content/generate"){let x=await body(req);let prompt=`You are AREA Maibab's Thai SEO editor. Primary market is Amphoe Mae Sai. Never invent price, review, inventory, delivery area or business claims. Return JSON only with keys title, meta, content, primaryKeyword, secondaryKeywords, intent. Service: ${x.service||"construction equipment rental"}. Topic: ${x.topic||"choose a useful non-duplicate local customer question"}. Content must be helpful Thai Markdown with H2 sections and FAQ.`;return json(res,200,await gemini(prompt))}
 return json(res,404,{error:"API not found"});
}catch(e){return json(res,500,{error:e.message})}};
http.createServer((req,res)=>{const u=new URL(req.url,"http://localhost");if(u.pathname.startsWith("/api/"))return api(req,res,u);let rel=u.pathname==="/"?"/index.html":u.pathname,file=path.normalize(path.join(root,rel));if(!file.startsWith(root)){res.writeHead(403);return res.end("Forbidden")}fs.readFile(file,(e,d)=>{if(e){res.writeHead(404);return res.end("Not found")}res.setHeader("Content-Type",file.endsWith(".css")?"text/css":file.endsWith(".js")?"text/javascript":"text/html; charset=utf-8");res.end(d)})}).listen(port,()=>console.log("AREA SEO AI v0.2 : "+port));
